### ISSUE TITLE
Add mirror for downloading nasm

### ISSUE THREAD

**Issue by jonaski** [ilammy/setup-nasm#22]
Could you add a mirror for downloading nasm, www.nasm.us is often down. Like right now.

```
Run ilammy/setup-nasm@v1
Downloading binary distribution...
binaries did not work: FetchError: request to https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip failed, reason: connect ETIMEDOUT 198.137.202.136:443
Downloading source code...
Warning: source code did not work: FetchError: request to https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.gz failed, reason: connect ETIMEDOUT 198.137.202.136:443
Error: could not install NASM: Error: I'm sorry, Dave. I'm afraid I can't do that.
```

**Comment by ilammy** [comment]
Thanks for a report, @jonaski!

I've pushed `ilammy/setup-nasm@v1.3.0` (aliased as `v1`) which uses a mirror from this very repo. Not *very* redundant – it will go down if GitHub goes down, but that's better that nothing. More mirrors can be easily added later if that's not enough.

I believe using `actions/tool-cache` (see #1) is the "right" way to do this, but I never found motivation to explore it :(

**Comment by jonaski** [comment]
Thanks.
