### ISSUE TITLE
Please update the following actions to use Node.js 16: ilammy/setup-nasm

### ISSUE THREAD

**Issue by c72578** [ilammy/setup-nasm#30]
Annotations
1 warning
build (windows-2019)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: ilammy/setup-nasm

**Comment by ilammy** [comment]
Thanks for a report 👍

Now using Node.js 16 since v1.4.0.

**Comment by c72578** [comment]
OK, thanks.
